version: "3"

services:
  gqlsql:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
